# Generated by Django 2.2.3 on 2019-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_rater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='daterate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date rated'),
        ),
        migrations.AlterField(
            model_name='ramen',
            name='style',
            field=models.CharField(choices=[('bar', 'Bar'), ('cup', 'Cup'), ('box', 'Box'), ('bowl', 'Bowl'), ('can', 'Can'), ('tray', 'Tray'), ('pack', 'Pack')], max_length=7),
        ),
    ]
