# Generated by Django 2.2.3 on 2019-09-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_rater', '0003_auto_20190918_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='daterate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
