# Generated by Django 2.2.3 on 2019-09-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_rater', '0004_auto_20190918_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='daterate',
            field=models.DateTimeField(blank=True, default='2019-09-18 19:06:17'),
        ),
    ]
