# Generated by Django 2.2.3 on 2019-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_rater', '0005_auto_20190918_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='daterate',
            field=models.DateTimeField(blank=True, default='2019-09-18 19:49:18'),
        ),
    ]
