# Generated by Django 2.2.5 on 2019-09-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramen_rater', '0007_auto_20190918_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ramen',
            name='daterate',
            field=models.DateTimeField(blank=True, default='2019-09-22 23:49:34'),
        ),
    ]
